name: Test

on: [pull_request]

jobs:
  misspell:
    name: runner / test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run: brew update
      - run: brew bundle
